buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.11.0'
    }
}

allprojects {
    repositories {
        jcenter()
        /*maven {
            url  "http://tokbox.bintray.com/maven"
        }*/
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.opentok.android:opentok-android-sdk:2.31.1'
} 
